.TH TO_MSGPACK 1 2021-10-29 "" "Serialize any object into messagepack"
.SH NAME
to_msgpack \- to_msgpack(x, schema = NULL)
.SH SYNOPSIS
\fIto_msgpack(x, schema = NULL)\fR
.SH OPTIONS
.PP
\fBx\fB \fR\- . any ``R#`` object
.PP
.PP
\fBschema\fB \fR\- NULL. a schema for serialization object x to messagepack.
.PP
.SH VALUE
.PP
data stream object
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.to_msgpack at msgpack.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
