.TH UNPACK 1 2021-10-29 "" "Deserialize object from messagepack data"
.SH NAME
unpack \- unpack(buffer)
.SH SYNOPSIS
\fIunpack(buffer)\fR
.SH OPTIONS
.PP
\fBbuffer\fB \fR\- . the binary stream data
.PP
.SH VALUE
.PP
R# object that read from the binary stream data in messagepack data format.
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.unpack at msgpack.R:line 20
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2021
