-- MySQL Script generated by MySQL Workbench
-- Sat May  6 22:44:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pkg_registry
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pkg_registry` ;

-- -----------------------------------------------------
-- Schema pkg_registry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pkg_registry` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pkg_registry` ;

-- -----------------------------------------------------
-- Table `dependency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dependency` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dependency` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pkg_id` INT UNSIGNED NOT NULL,
  `dependency_id` INT UNSIGNED NOT NULL,
  `version_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'the package dependency tree';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `dependency` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `packages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `packages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL COMMENT 'the package name',
  `author` VARCHAR(255) NOT NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `packages` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `packages` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `publish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publish` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `publish` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pkg_id` INT UNSIGNED NOT NULL,
  `pkg_name` VARCHAR(255) NOT NULL,
  `title` VARCHAR(1024) NOT NULL,
  `version` VARCHAR(64) NOT NULL DEFAULT '1.0.0',
  `description` VARCHAR(45) NULL,
  `release_note` VARCHAR(45) NULL,
  `add_time` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `publish` (`id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `package_reference` ON `publish` (`pkg_name` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
